### PR TITLE
Adds file exec method with progress

### PR DESCRIPTION
**Pull request by matthopson**
I went back and forth on how to best implement some better file features and decided to create a new Collection method for files specifically. This will keep the file handling logic out of our other operations and hopefully provide a little safety net as we expand on this.

So with this, you can call something like `teamsnap.collections.teamsPreferences.file('uploadTeamPhoto', params, progress)` 

And then your handler function would look something like this:
function (progress){
  return progress // returns an object containing `loaded` and `total`
}

### CODE REVIEW

**Comment by dmccraw** [comment]
So I am testing this out right now and let you know. I like how you added it to ScopedCollection and the MetaList.

**Comment by jjmocko** [comment]
excellent.. I just deployed the APIv3 updated broadcast_email_attachments endpoint to accept the file along with the object parameters (action: 'upload_attachment'). I'll be able to test this out tomorrow on the messages tab

:+1: looks good though

**Comment by matthopson** [comment]
Thanks! I'll have some working examples of this in action tomorrow.

**Comment by dmccraw** [comment]
@jjmocko I am actually working on the new broadcast_email_attachments right now. Will let you know what I find.

**Comment by dmccraw** [comment]
I think I got it to work! @jjmocko You need to change the register endpoint for broadcast_email_attachments and the broadcast_email_attachments_serializer. Right now they are pointing to `upload_attachment` but your route is actually `upload_broadcast_email_attachment`

I was able to upload a file with the following code in nextjenn:

```coffeescript
tryProgress = (progress) ->
  console.log(progress)

params = {
 broadcastEmailId: email.id
 memberId: controller.me.id
 file: controller.emailAttachment
}
teamsnap.collections.broadcastEmailAttachments.file("uploadBroadcastEmailAttachment", params, tryProgress)
```

I will add the code to teamsnap javascript sdk for uploading the file. 
@matthopson The progress callback worked. Console logging the `progress` param on the `tryProgress` callback resulted with: 
```javascript
Object {loaded: 622592, total: 1836088}
Object {loaded: 622592, total: 1836088}
Object {loaded: 1836088, total: 1836088}
Object {loaded: 1836088, total: 1836088}
````

**Comment by dmccraw** [comment]
@matthopson If I am uploading multiple files at one time, how can I differentiate between the progress callbacks?

**Comment by jjmocko** [comment]
Yes! awesome to hear :) I completely forgot about the name change to `upload_broadcast_email_attachment` due to @glanotte being the naming master

**Comment by matthopson** [comment]
@dmccraw I haven't worked on multi-file yet - that's my next step.

**Comment by matthopson** [comment]
@dmccraw We happy with this so far?

**Comment by dmccraw** [comment]
@matthopson :+1:

**Pull request merged**
