### PR TITLE
Load team fees when a roster member is created or deleted

### PR DESCRIPTION
**Pull request by amberwebb**
Fixes https://github.com/teamsnap/nextjenn-web/issues/1217

### CODE REVIEW

**Comment by dmccraw** [comment]
:ship: it! Looks good.

**Comment by matthopson** [comment]
Why reload `team_fees` when creating a new member?

**Comment by amberwebb** [comment]
@matthopson When a new member is created or deleted, the team fee is not updated on the payments tab until refresh. Is there another way to do this?

**Comment by matthopson** [comment]
The team fee should have nothing to do with the member, though.

**Comment by amberwebb** [comment]
So the wrapper methods are specifically for the object. `saveMember` and `deleteMember` are only for objects related to member.

**Comment by matthopson** [comment]
Yeah, and a `team_fee` object is completely independent of a member - if this is fixing an issue you're having, it's likely just masking something else. Let's look closer after DD.

**Comment by amberwebb** [comment]
Ok. Closing.

**Comment by matthopson** [comment]
:+1: I missed the `balance` portion of it. Disregard my dumb.

**Pull request merged**
