### PR TITLE
Fix security vulnerability alerts

### PR DESCRIPTION
**Pull request by VEkh**
Fixes all but two low priority security vulnerabilities that are only related to Brunch (asset builder).

Co-authored-by: Dorian Karter <dorian@hashrocket.com>
Co-authored-by: Vidal Ekechukwu <vidal@hashrocket.com>

### CODE REVIEW

**Comment by ryanwi** [comment]
Can you describe the testing done and what steps you recommend for regression testing and/or 
branch deploy?

Does the package.json itself get a version bump with these changes to 1.60.0?

Possible to publish a release candidate to NPM to enable testing?  For example, would we publish this as v1.60.0-beta or something?

**Comment by VEkh** [comment]
> Can you describe the testing done and what steps you recommend for regression testing and/or
> branch deploy?
> 

> Does the package.json itself get a version bump with these changes to 1.60.0?
> 
> Possible to publish a release candidate to NPM to enable testing? For example, would we publish this as v1.60.0-beta or something?

@ryanwi

**Comment by VEkh** [comment]
@ryanwi 

> Can you describe the testing done and what steps you recommend for regression testing and/or
> branch deploy?

We have smoke tested locally that everything is still working. We can deploy to our staging pod and do the same / have @lisa-intardonato run regression on it.

> Does the package.json itself get a version bump with these changes to 1.60.0?

The package.json version (1.59.0) on master is already bigger than what's on npm (1.58.0).

> Possible to publish a release candidate to NPM to enable testing? For example, would we publish this as v1.60.0-beta or something?

That seems unnecessary to us, but if you want to do that it's ok.

**Comment by dmccraw** [comment]
@VEkh I like the idea of having Lisa test it on the pod. We do have a lot of users the hit our frontend code and any update needs to be closely watched.

After looking this over I would have thought updating the dependencies would have had more effect on `teamsnap.js`. If rebuilding `teamsnap.js` with these new dependencies only makes the small amount of changes we are seeing then I am pretty comfortable with this pr.

**Comment by VEkh** [comment]
@dmccraw Allison did another pass on this and everything seems to work great! We are merging it in and are ready for you to push the update to NPM.

**Pull request merged**
