### PR TITLE
Add sendingMemberId param to sendAssignmentEmails

### PR DESCRIPTION
**Pull request by amberwebb**

### CODE REVIEW

**Comment by nathanielvelez** [comment]
I am not seeing the compiled teamsnap.js file

**Comment by nathanielvelez** [comment]
Another question. Is this NJW stuff that would be using it be behind a rollout? If the old stuff that don't send a `sendingMemberId` will still be around it would feel after we update to this version of the SJK.

**Comment by amberwebb** [comment]
@nathanielvelez `sendAssignmentEmails` is only available behind the assignments rollout.

**Comment by nathanielvelez** [comment]
👍

**Pull request merged**
