### PR TITLE
remove divisionTeamStanding as a teamType

### PR DESCRIPTION
**Pull request by dmccraw**

### CODE REVIEW

**Comment by glanotte** [comment]
seems right to me :+1:

**Comment by matthopson** [comment]
So this works if we want to pull it from the SDK - but it seems we probably want to pull it from NJ instead... or are you not going to be bulk loading this later @dmccraw?

**Comment by dmccraw** [comment]
I think we should pull it from the bulk_loader for now until we figure out what we want to do with all the division/league information.

**Comment by dmccraw** [comment]
Moving this change to nextjenn

**Pull request closed without merging**
