### PR TITLE
Load filters

### PR DESCRIPTION
**Pull request by matthopson**
Fixes a bug where filters weren't properly parsed when using "smart load" params.

Example:
```javascript
bulkLoad({teamId: 1, types: [member, contact], scopeTo: member, member__id: 1});
```

Without this fix, the `member__id: 1 filter` won't be added to the request.

### CODE REVIEW

**Comment by nathanielvelez** [comment]
It is missing the compiled `teamsnap.js`

**Comment by matthopson** [comment]
@nathanielvelez Ha.. yeah... I never commit the the compiled files for initial PR - just to make it easier to read - and prevent having to keep compiling / committing if there are changes.

**Comment by matthopson** [comment]
@nathanielvelez There. Pushed em up!

**Comment by nathanielvelez** [comment]
Cool. 👍  then.

**Pull request merged**
